from .autoencoder import SnapshotAutoencoder, SnapshotScaler, resolve_activation, train_autoencoder
from .benchmark import (
    BenchmarkConfig,
    build_offline_artifact,
    evaluate_benchmark_from_offline_artifact,
    load_or_build_offline_artifact,
    offline_artifact_cache_key,
    offline_artifact_cache_path,
    run_benchmark,
)
from .manifold_rom import ManifoldGalerkinROM, ManifoldLSPGROM
from .objective_ablation import (
    ObjectiveAblationMode,
    ObjectiveAblationStudyConfig,
    format_objective_ablation_study_markdown,
    pick_objective_ablation_recommendations,
    run_objective_ablation_study,
)
from .objective_weight_study import (
    ObjectiveWeightConfig,
    ObjectiveWeightStudyConfig,
    default_objective_weight_configs_for_preset,
    format_objective_weight_study_markdown,
    pick_objective_weight_recommendations,
    run_objective_weight_case,
    run_objective_weight_study,
)
from .pod_rom import PODGalerkinROM, PODLSPGROM
from .presets import get_benchmark_preset, list_benchmark_presets
from .preset_tuning import (
    PresetTuningCandidate,
    PresetTuningStudyConfig,
    format_preset_tuning_study_markdown,
    pick_preset_tuning_recommendations,
    run_preset_tuning_study,
)
from .problems import (
    BratuSourceProblem,
    FrontLayerProblem,
    HydrologicConductivityProblem,
    NonlinearDiffusionProblem,
    create_problem,
)
from .reference_study import (
    ReferenceArchitectureStudyConfig,
    format_reference_architecture_study_markdown,
    pick_reference_architecture_decisions,
    run_reference_architecture_study,
)
from .sweep import (
    SweepConfig,
    parse_float_tuple,
    parse_hidden_dims_options,
    parse_int_tuple,
    parse_str_tuple,
    run_sweep,
)
from .solver_tradeoff import (
    SolverTradeoffStudyConfig,
    build_solver_tradeoff_benchmark_config,
    build_solver_tradeoff_payload,
    format_solver_tradeoff_study_markdown,
    pick_solver_recommendation,
    run_solver_tradeoff_case,
    run_solver_tradeoff_study,
)
from .transient import (
    TransientBenchmarkConfig,
    TransientFrontLayerProblem,
    run_transient_benchmark,
)

__all__ = [
    "BenchmarkConfig",
    "BratuSourceProblem",
    "FrontLayerProblem",
    "HydrologicConductivityProblem",
    "ManifoldGalerkinROM",
    "ManifoldLSPGROM",
    "NonlinearDiffusionProblem",
    "ObjectiveAblationMode",
    "ObjectiveAblationStudyConfig",
    "ObjectiveWeightConfig",
    "ObjectiveWeightStudyConfig",
    "PODGalerkinROM",
    "PODLSPGROM",
    "PresetTuningCandidate",
    "PresetTuningStudyConfig",
    "ReferenceArchitectureStudyConfig",
    "SweepConfig",
    "SnapshotAutoencoder",
    "SnapshotScaler",
    "SolverTradeoffStudyConfig",
    "TransientBenchmarkConfig",
    "TransientFrontLayerProblem",
    "build_solver_tradeoff_benchmark_config",
    "build_solver_tradeoff_payload",
    "build_offline_artifact",
    "evaluate_benchmark_from_offline_artifact",
    "get_benchmark_preset",
    "list_benchmark_presets",
    "load_or_build_offline_artifact",
    "offline_artifact_cache_key",
    "offline_artifact_cache_path",
    "resolve_activation",
    "create_problem",
    "parse_float_tuple",
    "parse_hidden_dims_options",
    "parse_int_tuple",
    "parse_str_tuple",
    "pick_reference_architecture_decisions",
    "pick_solver_recommendation",
    "pick_preset_tuning_recommendations",
    "format_reference_architecture_study_markdown",
    "format_solver_tradeoff_study_markdown",
    "format_preset_tuning_study_markdown",
    "run_benchmark",
    "format_objective_ablation_study_markdown",
    "format_objective_weight_study_markdown",
    "pick_objective_ablation_recommendations",
    "pick_objective_weight_recommendations",
    "run_objective_ablation_study",
    "run_objective_weight_case",
    "run_objective_weight_study",
    "run_preset_tuning_study",
    "run_reference_architecture_study",
    "run_solver_tradeoff_study",
    "run_solver_tradeoff_case",
    "run_sweep",
    "run_transient_benchmark",
    "train_autoencoder",
    "default_objective_weight_configs_for_preset",
]
